package exception;

public class Test {

	public static void main(String[] args) {

          try {
	        int i;
			return;
			}
			catch(Exception e){
			System.out.print("CatchBlock");
			}
			finally{
			System.out.println("FinallyBlock");
			}
			}
			}

